### ISSUE TITLE
Don't show info gateway

### ISSUE THREAD

**Issue by armandomuassab** [JOHLC/pfSense-FauxAPI-ha#10]
Don't showing information gateways

**Comment by armandomuassab** [comment]
![Gateway](https://user-images.githubusercontent.com/49219238/115312580-f4fe7980-a147-11eb-8b29-2bcb5ac193fa.png)

**Comment by JOHLC** [comment]
I see,

Did you follow the comment about changing the WAN interface name if yours doesn't use IGB0?

**Comment by JOHLC** [comment]
What does your fauxapi config look like? (Exclude your keys)

**Comment by JOHLC** [comment]
Please also review the breaking changes and [configuration changes](https://github.com/JOHLC/pfSense-FauxAPI-ha#configure-your-secretsyaml-with-the-appropriate-python-commands) required for the [latest release](https://github.com/JOHLC/pfSense-FauxAPI-ha/releases/tag/v20210424.1)

**Comment by pex81** [comment]
Hi, i have the same problem after update.
Only with this sensor:
```
  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN GB in
    value_template: '{{ (value_json[int_status]["data"]["stats"]["inbytes"] | float / 1000 / 1000 / 1000) | round(2)}}'
    scan_interval: 60
    unit_of_measurement: GB

  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN GB out
    value_template: '{{ (value_json[int_status]["data"]["stats"]["outbytes"] | float / 1000 / 1000 / 1000) | round(2)}}'
    scan_interval: 60
    unit_of_measurement: GB
```

**Comment by JOHLC** [comment]
Ah ha! 
I will take a look at this as soon as I can.

**Comment by JOHLC** [comment]
Looks like this was an issue on my end as well, I just didn't notice 

int_status was missing quotes [int_status] instead of ["int_status"] 🤦‍♂️

````
  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN GB in
    value_template: '{{ (value_json["int_status"]["data"]["stats"]["inbytes"] | float / 1000 / 1000 / 1000) | round(2)}}'
    scan_interval: 60
    unit_of_measurement: GB

  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN GB out
    value_template: '{{ (value_json["int_status"]["data"]["stats"]["outbytes"] | float / 1000 / 1000 / 1000) | round(2)}}'
    scan_interval: 60
    unit_of_measurement: GB
````

Please try this and test, it looks like that fixed it for me
![image](https://user-images.githubusercontent.com/63735432/116118609-7e9fd100-a68b-11eb-98ae-728417ba6842.png)
****

**Comment by pex81** [comment]
> Looks like this was an issue on my end as well, I just didn't notice
> 
> int_status was missing quotes [int_status] instead of ["int_status"] 🤦‍♂️
> 
> ```
>   - platform: command_line
>     command: !secret pf_api_command
>     name: pfSense WAN GB in
>     value_template: '{{ (value_json["int_status"]["data"]["stats"]["inbytes"] | float / 1000 / 1000 / 1000) | round(2)}}'
>     scan_interval: 60
>     unit_of_measurement: GB
> 
>   - platform: command_line
>     command: !secret pf_api_command
>     name: pfSense WAN GB out
>     value_template: '{{ (value_json["int_status"]["data"]["stats"]["outbytes"] | float / 1000 / 1000 / 1000) | round(2)}}'
>     scan_interval: 60
>     unit_of_measurement: GB
> ```
> 
> Please try this and test, it looks like that fixed it for me
> ![image](https://user-images.githubusercontent.com/63735432/116118609-7e9fd100-a68b-11eb-98ae-728417ba6842.png)

Thanks, problem solved!!!

**Comment by JOHLC** [comment]
> Thanks, problem solved!!!

Thanks for your help!

**Comment by armandomuassab** [comment]
For me problem persist

**Comment by JOHLC** [comment]
> For me problem persist

Even after updating your sensors to match the above ^  ?

**Comment by armandomuassab** [comment]
Yes. Even after changing. I can also change the interface to igb0 or pppoe0 that the result appears as unknown

**Comment by JOHLC** [comment]
If you run the command in ssh manually does it show any result?

**Comment by armandomuassab** [comment]
Can you guide me which command to run?

**Comment by JOHLC** [comment]
```
# You will need to change your host IP, apikey, and accesstoken in the command below
pf_api_command: "python3 /config/custom_components/pfsense_fauxapi/function-iterate.py 192.168.1.1 PFFAyourapikey youraccesstoken"
```

**Comment by armandomuassab** [comment]
yes...show the result

**Comment by JOHLC** [comment]
Can you post your configuration yaml entries for these sensors? 
![image](https://user-images.githubusercontent.com/63735432/116474108-134e2e80-a846-11eb-853f-17266a4f6016.png)

**Comment by armandomuassab** [comment]
where XXX.XXX.XXX.XX is the ip gateway that I got from pfsense  
 - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN IP
    value_template: '{{ value_json["gw_status"]["data"]["gateway_status"]["XXX.XXX.XXX.XX"]["srcip"] }}'
    scan_interval: 300
    
  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN packetloss
    value_template: '{{ (value_json["gw_status"]["data"]["gateway_status"]["XXX.XXX.XXX.XX"]["loss"]) | regex_replace(find="%",replace="",ignorecase=True) }}'
    unit_of_measurement: "%"
    scan_interval: 30

  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN status
    value_template: '{{ (value_json["gw_status"]["data"]["gateway_status"]["XXX.XXX.XXX.XX"]["status"]) }}'
    scan_interval: 30

  - platform: command_line
    command: !secret pf_api_command
    name: pfSense WAN latency
    value_template: '{{ (value_json["gw_status"]["data"]["gateway_status"]["XXX.XXX.XXX.XX"]["delay"]) | regex_replace(find="ms",replace="",ignorecase=True) }}' 
    unit_of_measurement: "ms"
    scan_interval: 60

**Comment by armandomuassab** [comment]
I discovered the problem. In my pfsense my gateway needs an ip monitor, so I needed to replace the monitor's ip in place of "your.gw.ip.address" ... now it worked.
I only succeeded after analyzing the result of the ssh command that you indicated to me.
Thank you very much.
