### ISSUE TITLE
Instruction Update

### ISSUE THREAD

**Issue by Strider11** [JOHLC/pfSense-FauxAPI-ha#13]
I spent multiple days trying to figure out why I couldn't get this working. Only to find out that I had PFSense setup as HTTP access, when FauxAPI requires HTTPS. Could you add a note to the installation instructions to prevent some other n00b from making my same mistake?

**Comment by JOHLC** [comment]
Done
````
Prerequisites
A device with pfSense installed - tested with v2.5 CE
Web access should be configured with ssl/https encryption and a certificate
FauxAPI installed on your pfSense instance, configured with an API key and access to
````
