### ISSUE TITLE
interest in collaborating using the real xmlrpc api

### ISSUE THREAD

**Issue by travisghansen** [JOHLC/pfSense-FauxAPI-ha#14]
pfSense does indeed have a legit xmlrpc api. Would you have any interest in migrating this to use that instead of fauxapi? I have fairly extensive experience using it as I’ve built other integrations (ie: https://github.com/travisghansen/kubernetes-pfsense-controller and other non public tools) leveraging it.

**Comment by JOHLC** [comment]
Is there something this does better? 
Would it support the same functions? 
Any experience with creating components for Home Assistant? 

In the end, my vision would be for this to be a real component in Home Assistant with config flows and automatic setup etc. but my python skills are non-existent.

Going to close this as it isn't so much a bug or feature request but a discussion. Moved here:  #18

**Comment by travisghansen** [comment]
https://github.com/travisghansen/hass-pfsense
