### ISSUE TITLE
HACS Compatibility

### ISSUE THREAD

**Issue by meichthys** [JOHLC/pfSense-FauxAPI-ha#3]
It would be really nice if this was available to install via HACS. 
If i get time i may try to submit a pull request to provide HACS compatibility, but the guidelines are listed here: https://hacs.xyz/docs/publish/start

**Comment by JOHLC** [comment]
added and released v0.1b **https://github.com/JOHLC/pfSense-FauxAPI-ha/releases/tag/v0.1b**

**Comment by JOHLC** [comment]
Note: you will likely want to adjust your configs to the new example

**Comment by meichthys** [comment]
Awesome. Thanks! I'll check it out! The Wan stats are so useful.
