### ISSUE TITLE
How to use python3 command in HomeAssistant

### ISSUE THREAD

**Issue by tomatoinaction** [JOHLC/pfSense-FauxAPI-ha#8]
Thanks for this great repo.
My Problem is that i dont get it how to activate in HomeAssistant to use python3 from the command line.
There are a bunch of intergrations but they seem not to work the way it should with this addon here.

Can you tell how you have done this.

Thanks and have a nice day

**Comment by JOHLC** [comment]
I am running Home Assistant supervised which seemingly included the python3 command in the command line 
![image](https://user-images.githubusercontent.com/63735432/106540723-7db53400-64ce-11eb-8672-711ccfded796.png)

Then, per the documentation for this, I add the command line sensors / commands to Home Assistant
https://github.com/JOHLC/pfSense-FauxAPI-ha#2-configure-your-sensors-and-commands

How do you have Home Assistant installed?

**Comment by tomatoinaction** [comment]
Logger: homeassistant.components.command_line
Source: components/command_line/__init__.py:41
Integration: command_line (documentation, issues)
First occurred: 31. Januar 2021, 17:59:02 (36809 occurrences)
Last logged: 8:09:41

Command failed: python3 /config/custom_components/pfsense_fauxapi/function-info.py xxx yyy zzz
Command failed: python3 /config/custom_components/pfsense_fauxapi/function-stats.py  xxx yyy zzz
Command failed: python3 /config/custom_components/pfsense_fauxapi/function-gateway.py  xxx yyy zzz
Command failed: python3 /config/custom_components/pfsense_fauxapi/function-int-wan.py  xxx yyy zzz

![image](https://user-images.githubusercontent.com/44731882/106565096-85a4c080-652e-11eb-8105-233583034d4b.png)

**Comment by tomatoinaction** [comment]
This is the HomeAssistant VM from their page. With Supervisor and everything.
When i go in Terminal and type in 'python' or 'python3' i get nothing.
So what do you mean?

Kind regards

**Comment by JOHLC** [comment]
When you say you get nothing? 
Do you get an error message?

**Comment by tomatoinaction** [comment]
![20210203_202105](https://user-images.githubusercontent.com/44731882/106797824-6a849e80-665d-11eb-8cde-eb6fbc8d422a.jpg)

**Comment by JOHLC** [comment]
@tomatoinaction, check here for info https://www.home-assistant.io/faq/#pip3-command-not-found 

Other than that, I am not sure how to help.

**Comment by JOHLC** [comment]
Ever able to figure anything out @tomatoinaction ?

**Comment by tomatoinaction** [comment]
Sry dont have time and motivation to follow up the problem.
So i have cleaned up this addon and carried on with mqtt and snmp to get this data. 

Thanks for your help 🙂

**Comment by bogdanr** [comment]
I have the same issue:
```
~ $ ha info
arch: amd64
channel: stable
docker: 20.10.6
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- hassos
hassos: "6.2"
homeassistant: 2021.8.7
hostname: homeassistant
logging: info
machine: qemux86-64
operating_system: Home Assistant OS 6.2
state: running
supervisor: 2021.06.8
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Bucharest
```
```
~ $ python3 --version
-bash: python3: command not found
~ $ python --version
-bash: python: command not found
````
How do I get to use this with my instalation?

**Comment by bogdanr** [comment]
Instead of using "Terminal and SSH" for testing, it should be used "SSH & Web Terminal" and then python3 will be available.

**Comment by tomatoinaction** [comment]
> Instead of using "Terminal and SSH" for testing, it should be used "SSH & Web Terminal" and then python3 will be available.

Thanks for this! i will go on trying to implement this feature in my homeassistant!
